#!/bin/bash

#==================================================
# This simple script is to backup files using rsync
#================================================== 
#
# @27.02.2013 --- Henry Huang ---
# 
# to make sure rsync command really works the way you want, 
# try it with '--dry-run' option until you're satisfied 
# with what it is doing

DAY=`date "+%F"`

BACKUP_LIST="Work Documents Desktop Downloads public_html"
BACKUP_LOG=${DAY}_backup.log

DEST="/media/1808-456F/backup"

# create log files in the backup directory
touch ${DEST}/${BACKUP_LOG}

# start backing up files to destination on a spare disk
for d in $BACKUP_LIST; do
    rsync --dry-run -av --exclude Dropbox --delete /home/henry/$d/ $DEST/$d/ >> $DEST/${BACKUP_LOG} 2>&1
done
